on:
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (Jest + coverage)
      - name: Run tests
        run: npm test -- --coverage

      # Gitleaks scan
      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # SonarQube scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
         args: >
           -Dsonar.projectKey=samuel-nartey_my-js-app
           -Dsonar.organization=samuel-nartey
           -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
        
      #  Debug scan version
     # - name: SonarCloud Scan (Debug)
       # run: npx sonar-scanner -X
       # env:
       #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
